#!/bin/bash

## Terra's script for fresh Fedora installs.
## This will grab the following packages, as well as config files, and make
## necessary changes. Needs to be run as root.
##
## Basics
## - GroupInstall "Development Tools"
## - gnupg
## - git, Bazaar, and wget
## - automake, libtool
## - Java JDK and JRE
## 
## Command Line Tools
## - rxvt-unicode, tmux, zsh (Basics)
## - kpcli (KeePass CLI)
## - Emacs and emacs-goodies (Text Editor/Mini-OS)
## - Elinks (Web Browser)
## - Mutt and abook (email and address book)
## - calcurse (Calendar and time management)
## - weechat and bitlbee (IRC and IM client)
## - mc (Midnight Commander file manager)
## - htop (Better top replacement)
## 
## GUI tools
## - dropbox (File Sync)

## Run a full update

echo "Running an update."
yum -y update

## Grab the Development Tools group

read -p "Would you like to install the dev toolchain [Y/n]" devtoolask
if [[ $devtoolask =~ ^[yY]([eE][sS])$ ]]
then
yum -y groups install "Development Tools"
else
echo "Okay, moving on."
fi

## Grab the CLI stuff

echo "The CLI tools to be fetched include the following:"
echo "elinks, mutt, abook, calcurse, weechat, bitlbee, mc, htop,"
echo "gnupg, kpcli (with dependencies), phpcli, and emacs (with goodies),"
echo "mc, htop, git, bzr, wget, tmux, zsh, and youtube-dl"

read -p "Would you like to install these packages? [Y/n]" clitoolask
if [[ $clitoolask =~ ^([yY][eE][sS]|[yY])$ ]]
then
yum -y install elinks mutt abook calcurse weechat bitlbee mc htop gnupg kpcli perl-Clipboard perl-Capture-Tiny perl-Term-ReadLine-Gnu php-cli emacs emacs-goodies emacs-goodies-el mc htop git bzr wget tmux, zsh, youtube-dl
else
echo "Okay, moving on."
fi

## Grab the other stuff

echo "Other packages to be fetched include the following:"
echo "Java JDK and JRE, enlightenment, rxvt-unicode,"
echo "libtool, and automake."

read -p "Would you like to install these packages? [Y/n]" guitoolask
if [[ $guitoolask =~ ^([yY][eE][sS]|[yY])$ ]]
then
yum -y install java-1.7.0-openjdk java-1.7.0-openjdk-devel icedtea-web automake libtool enlightenment
else
echo "Okay, moving on."
fi

## Need the Japanese Support group as well

read -p "Do you need Japanese support? [Y/n]" japtoolask
if [[ $japtoolask =~ ^([yY][eE][sS]|[yY])$ ]]
then
yum -y groups install "Japanese Support"
else
echo "Okay, moving on."
fi

## Grab dropbox, extract it, grab the python script, and start the daemon

read -p "Should I get dropbox? [Y/n]" dropboxask

if [[ $dropboxask =~ ^([yY][eE][sS]|[yY])$ ]]
then
cd ~ 
wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
wget -O - "https://www.dropbox.com/download?dl=packages/dropbox.py" > dropbox.py
chmod +x dropbox.py
./dropbox.py start
else
echo "Okay, moving on."
fi

## Grab the git repos, then copy the config files into the home directory

read -p "Should I grab the github repos for teradyne-ezeri? [Y/n]" githubask

if [[ $githubask =~ ^([yY][eE][sS]|[yY])$ ]]
mkdir github_repos
cd ./github_repos
git clone https://github.com/teradyne-ezeri/scripts
git clone https://github.com/teradyne-ezeri/config-files
cd ./config-files 
cp -t ~/ .Xresources .tmux.conf .muttrc .zshrc .zshenv .emacs
xrdb -merge .Xresources
else
echo "Okay, moving on."
fi

## Set the shell to zsh, though it will need the password

read -p "Should I change the shell to zsh? [Y/n]" chshask
if [[ $chshask =~ ^([yY][eE][sS]|[yY])$ ]]
then
chsh -s /bin/zsh
else
echo "Okay, moving on."
fi

## Since Anaconda has a habit of ignoring hostname settings on install, set the 
## machine hostname

read -p "Do you need to change the hostname? [Y/n]" newhostask
if [[ $newhostask =~ ^([yY][eE][sS]|[yY])$ ]]
then 
read -p "Enter hostname for this system: " newhostname
su -c "echo $newhostname > /etc/hostname"
else
echo "Okay, nothing else needed."
fi
